export enum ItemMaterial {
    OTHER = "other",

    ORIGINIUM = "originium",
    ORIGINIUM_ENR = "originium_enr",
    AMETHYST = "amethyst",
    AMETHYST_ENR = "amethyst_enr",
    IRON = "iron",
    IRON_ENR = "iron_enr",
    COPPER = "copper",
    COPPER_ENR = "copper_enr",
    CARBON = "carbon",
    CARBON_ENR = "carbon_enr",
    WATER = "water",
    SEWAGE = "sewage",
    ACID = "acid",
    INERT = "inert",
    XIRANITE = "xiranite",
    XIRANITE_ENR = "xiranite_enr",

    PLANT_SP_1 = "plant_sp_1",
    PLANT_SP_2 = "plant_sp_2",
    PLANT_SP_3 = "plant_sp_3",
    PLANT_SP_4 = "plant_sp_4",
    PLANT_GRASS_1 = "plant_grass_1",
    PLANT_GRASS_2 = "plant_grass_2",
    PLANT_GRASS_SPC_1 = "plant_grass_spc_1",
    PLANT_GRASS_SPC_2 = "plant_grass_spc_2",
    PLANT_FLOWER_1 = "plant_flower_1",
    PLANT_FLOWER_2 = "plant_flower_2",
    PLANT_FLOWER_3 = "plant_flower_3",
    PLANT_FLOWER_SPC_1 = "plant_flower_spc_1",
    PLANT_FLOWER_SPC_2 = "plant_flower_spc_2",
    PLANT_BBFLOWER_1 = "plant_bbflower_1",
}